# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='negativ',
            field=models.BooleanField(default=False),
        ),
    ]
