# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_answeroption_negativ'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='label',
            field=models.SlugField(default='FOO', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='survey.Catalog'),
        ),
        migrations.AlterField(
            model_name='answerchoice',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.SlugField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
