# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 13:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0004_auto_20170405_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('finished', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='survey.Site')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='answerchoice',
            name='site',
        ),
        migrations.RemoveField(
            model_name='answerchoice',
            name='tester',
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='discussion_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='revision_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='evaluation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.SiteEvaluation'),
            preserve_default=False,
        ),
    ]
