# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20170405_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerchoice',
            name='prefix',
            field=models.SlugField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='siteevaluation',
            name='checklist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='survey.Checklist'),
            preserve_default=False,
        ),
    ]
