# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20170407_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerchoice',
            name='prefix',
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='path',
            field=models.ManyToManyField(related_name='_answerchoice_path_+', to='survey.Catalog'),
        ),
    ]
