# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20170407_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
