# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_checklist_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchoice',
            name='value',
            field=models.CharField(default='', max_length=200),
        ),
    ]
