# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 15:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0009_auto_20170502_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='name',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='version',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='siteevaluation',
            unique_together=set([('checklist', 'tester', 'site')]),
        ),
    ]
