# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20170505_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerchoice',
            name='full_label',
            field=models.SlugField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='survey.AnswerChoice'),
        ),
        migrations.RemoveField(
            model_name='answerchoice',
            name='path',
        ),
        migrations.AlterUniqueTogether(
            name='answerchoice',
            unique_together=set([('evaluation', 'full_label')]),
        ),
    ]
