# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20170507_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquestion',
            name='question_text',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
