# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_auto_20170511_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalquestion',
            name='_order',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterOrderWithRespectTo(
            name='question',
            order_with_respect_to='catalog',
        ),
    ]
