# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_auto_20170513_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerchoice',
            options={'ordering': ['id']},
        ),
    ]
