# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_auto_20170516_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalquestion',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='siteevaluation',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
