# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_auto_20170602_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerchoice',
            name='dirty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalanswerchoice',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalansweroption',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalquestion',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
