# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 08:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_auto_20170612_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ListingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ListingIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(default=datetime.date.today)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='survey.Listing', unique_for_date='pub_date')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSynonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('listing_issues', models.ManyToManyField(related_name='sites', through='survey.ListingEntry', to='survey.ListingIssue')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='survey.Site')),
            ],
        ),
        migrations.AddField(
            model_name='listingentry',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='survey.ListingIssue'),
        ),
        migrations.AddField(
            model_name='listingentry',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_entries', to='survey.SiteSynonym'),
        ),
        migrations.AlterUniqueTogether(
            name='listingentry',
            unique_together=set([('issue', 'site')]),
        ),
    ]
