# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_auto_20170629_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listingentry',
            options={'ordering': ['issue', 'rank']},
        ),
    ]
